---
- name: Install prerequisites
  yum:
    name: ["yum-utils", "device-mapper-persistent-data", "lvm2"]
    state: present

- name: Import Docker CE repository gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add repository
  yum_repository:
    name: docker-ce
    description: Docker CE repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable

- name: Install docker
  yum:
    name: 'docker-ce'
    state: latest
  notify: enable and start docker

- name: Install docker-compose
  yum:
    name: 'docker-compose'
    state: latest

- name: Add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

#- name: Copy docker-compose.yml to docker host
#  copy:
#    src: docker-compose.yml
#    dest: /srv/stack/docker-compose.yml

    #- name: Start docker-compose stack
    #docker_service:
    #project_src: /srv/stack/
